import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="mx-auto p-12">
          {children}
        </section>
        <footer>
          <p className="text-center text-sm text-gray-500">@ 2024</p>
        </footer>
      </body>
    </html>
  );
}
